# Generated by Django 5.1.8 on 2025-05-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_preview_base64',
            field=models.TextField(blank=True, editable=False, help_text='Base64 encoded first 4 lines of the document content for preview.', null=True, verbose_name='content preview base64'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('document', 'Document'), ('presentation', 'Presentation')], default='document', help_text='The type of the document, e.g., a regular document or a presentation.', max_length=40, verbose_name='document type'),
        ),
    ]
